//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelaninaPrata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cidade
    {
        public int id { get; set; }
        public Nullable<int> codigoIBGE { get; set; }
        public string nome { get; set; }
        public Nullable<int> uf { get; set; }
    }
}
