//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelaninaPrata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoa
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public Nullable<System.DateTime> nascimento { get; set; }
        public Nullable<decimal> comissao { get; set; }
        public string endereco { get; set; }
        public string complemento { get; set; }
        public string numEndereco { get; set; }
        public string cep { get; set; }
        public string codigoCidade { get; set; }
        public Nullable<int> uf { get; set; }
        public string telefone { get; set; }
    }
}
