//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelaninaPrata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public string referencia { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<decimal> custo { get; set; }
        public Nullable<int> grupoId { get; set; }
    
        public virtual grupos grupos { get; set; }
    }
}
